lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  favicon: /favicon/favicon_ihourglass.jpg
  title: "Hourglass"
  description: "Маркетинг, основанный на данных. Реклама и аналитика в интернете"
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: " "
      - href: services.qmd
        text: "Услуги"
      - href: cases.qmd
        text: "Кейсы"  
      - href: wiki.qmd
        text: "Wiki"
      - href: contacts.qmd
        text: "Контакты"
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Коршаков Александр
    right: Сайт создан с помощью [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  cookie-consent:
    type: implied
    style: simple
    palette: light

format:
  html:
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    theme: minty
    include-in-header: scripts/gtm_head.html
    include-after-body: scripts/gtm_body.html

execute:
  freeze: auto