lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  favicon: /favicon/favicon_ihourglass.jpg
  title: "ihourglass"
  description: "Маркетинг, основанный на данных. Реклама и аналитика в интернете"
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: " "
      - href: services.qmd
        text: "Услуги"
      - href: wiki.qmd
        text: "Wiki"
      - href: contacts.qmd
        text: "Контакты"
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Коршаков Александр
    right: Сайт создан с помощью [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "GTM-KB6J3FZF"
    anonymize-ip: false

format:
  html:
    toc: true
    toc-location: left
    cap-location: top
    css: styles.css
    link-external-newwindow: true
    theme: minty

execute: 
  freeze: auto