project:
  type: website
  output-dir: docs

website:
  title: "PLATZKART BI"
  description: "Система отслеживания результатов ведения проектов"
  navbar:
    left:
      - href: index.qmd
        text: "О проекте"
      - reports.qmd
  page-footer:
    center: 
      - text: "Reports"
        href: reports.qmd
      

format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    html-math-method: katex

editor: visual

