lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    

website:
  google-analytics:
    tracking-id: "GTM-KB6J3FZF"
    
  title: "Data Driven Marketing"
  description: "Маркетинг, основанный на данных. Реклама и аналитика в интернете"
  navbar:
    left:
      - href: index.qmd
        text: "Главная"
      - href: about/korshakov.qmd
        text: "О себе" 
      - href: wiki.qmd
        text: "Wiki"
      - href: contacts.qmd
        text: "Контакты"

format:
  html:
    toc: true
    toc-location: left
    css: styles.css
    link-external-newwindow: true
    theme: minty

execute: 
  freeze: auto
    


