project:
  type: website
  output-dir: docs
lang: ru

website:
  title: "PLATZKART BI"
  description: "Система отслеживания результатов ведения проектов"
  navbar:
    left:
      - href: index.qmd
        text: "О проекте"
      - reports.qmd
  page-footer:
    center: 
      - text: "Reports"
        href: reports.qmd
format:
  html:
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css

