lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "!clients/"
    - "*.qmd"
    

website:
  title: "Korshakov Consulting"
  description: "Консалтинговые услуги в сфере маркетинга и рекламы"
  navbar:
    left:
      - href: index.qmd
        text: "Главная"
      - href: case/cases.qmd
        text: "Кейсы"

format:
  html:
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css
    link-external-newwindow: true
    theme: minty


