lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "!reports/pator/"
    - "*.qmd"
    

website:
  title: "PLATZKART BI"
  description: "Система отслеживания результатов ведения проектов"
  navbar:
    left:
      - href: index.qmd
        text: "О проекте"

format:
  html:
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css

