lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "!clients/pator/"
    - "!clients/mc/"
    - "*.qmd"
    

website:
  title: "Korshakov Consulting"
  description: "Консалтинговые услуги в сфере маркетинга и рекламы"
  navbar:
    left:
      - href: index.qmd
        text: "Главная"

format:
  html:
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css

