lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!reports/pator/"


website:
  title: "PLATZKART BI"
  description: "Система отслеживания результатов ведения проектов"
  navbar:
    left:
      - href: index.qmd
        text: "О проекте"
      - reports/reports.qmd

format:
  html:
    self-contained: true
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css

