lang: ru

project:
  type: website
  output-dir: docs
  render:
    - "!clients/"
    - "*.qmd"
    

website:
  title: "Korshakoff Consulting"
  description: "Консалтинговые услуги в сфере маркетинга и рекламы"
  navbar:
    left:
      - href: index.qmd
        text: "Главная"
      - href: cases.qmd
        text: "Кейсы"

format:
  html:
    toc: true
    toc-location: left
    css: styles.css
    link-external-newwindow: true
    theme: minty

    


