---
title: "Wiki"

editor_options: 
  chunk_output_type: console
---

## Реклама

* [Как продавать сложные продукты в В2В в условиях кризиса с минимальным бюджетом](https://platzkart.ru/portfolio/case-mtz/)

* [Экономим рекламный бюджет с помощью кластерного анализа площадок в рекламных сетях Яндекса](/wiki/ds_places_analysis.html)

* [Применяем ГОСТ стандарт РФ «Контрольные карты Шухарта» для оптимизация рекламных кампаний и других источников трафика](/wiki/shewhart_control_card.html)

* [Как выбрать микроцель для обучения стратегии показов объявлений в любой рекламной системе. Часть 1. Корреляция и регрессия. Подробный разбор методологии с примерами](/wiki/correlatio.html)

* [Как выбрать микроцель для обучения стратегии показов объявлений в любой рекламной системе. Часть 2. Статистика оценок или почему не надо испольлзовать только метод проверки значимости нулевой гипотезы, основанный на p-value.](/wiki/correlatio_part_2_new_statistics.html)


## Маркетинг

* [Ситуационный анализ и сратегическая канва в недвижимости](https://platzkart.ru/portfolio/case-nedvizhimost-krasnodar/)


## Анализ данных

* [Как проверить качество входящих звонков из рекламных кампаний, если нет CRM-системы и времени прослушивать каждый звонок](/wiki/call_analysis.html)